language: minimal

# Disable git shallow clone. We need full history for validating copyright year of each file.
git:
    depth: false

dist: trusty

before_script:
    - git clone git://github.com/mendersoftware/mendertesting

    # Rename the branch we're on, so that it's not in the way for the
    # subsequent fetch. It's ok if this fails, it just means we're not on any
    # branch.
    - git branch -m temp-branch || true
    # Git trick: Fetch directly into our local branches instead of remote
    # branches.
    - git fetch origin 'refs/heads/*:refs/heads/*'
    # Get last remaining tags, if any.
    - git fetch --tags origin

script:
    # Check commit compliance.
    - mendertesting/check_commits.sh
    # Check licenses
    - mendertesting/check_license.sh
    - ./docker-build
